### ISSUE TITLE
Report not possible in JSON format

### ISSUE THREAD

**Issue by RaphaelVogel** [SAP/fosstars-rating-core#996]
I try to run the scanner locally using this guide: https://github.com/SAP/fosstars-oss-rules-of-play-report/blob/main/running-locally.md

I configured the scanner with the following config file for test purposes:
```
cache: .fosstars/project_rating_cache.json
reports:
  - type: json
    where: ./
finder:
  # To scan a full organization use the organizations object
  #organizations:
  #  - name: gardener
  #    exclude:
  #      - .github
  #      - .repository-template
  # To scan a single repository use the repositories object
  repositories:
  - organization: gardener
    name: alpine-conntrack
```
 
In the log I get the following error message:
“Oops! That's an unknown type of report: JSON”
